name: Unpublish GitHub Pages

on:
  workflow_dispatch:

jobs:
  unpublish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove gh-pages branch (unpublish)
        run: |
          git fetch origin
          git push origin --delete gh-pages
          git branch -D gh-pages
